spring:
  application:
    name: finance-tracker-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finance_tracker}
    username: ${DB_USER:finance_user}
    password: ${DB_PASS:finance_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET search_path TO ods, ref, rpt, public"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: ${PORT:8080}

ollama:
  base-url: ${OLLAMA_URL:http://172.17.0.1:11434}
  model: ${OLLAMA_MODEL:gemma4:e2b}
  timeout-seconds: 120
