spring.application.name=FinancialTrackerAPI
# Azure SQL Database Configuration
# application.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Optional Hibernate/JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
##config for local build
#spring.datasource.url=jdbc:sqlserver://localhost:13001;databaseName=Finance_Tracker;encrypt=false;trustServerCertificate=false
#spring.datasource.username=SA
#spring.datasource.password=PH@123456789
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


##config for docker build
#spring.datasource.url=jdbc:sqlserver://host.docker.internal:13001;databaseName=Finance_Tracker;encrypt=false;trustServerCertificate=false
#spring.datasource.username=SA
#spring.datasource.password=PH@123456789
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver